// ============================================================================
//  CLUSTER-9 — auto-scaffolded from cluster - 9.svg
// ============================================================================
//  Generated by scripts/scaffold-cluster.mjs. Refine via the position editor
//  at http://localhost:5173/#cluster-9 (add text elements, drag positions,
//  tune media offset/scale/crop). All editable values live in
//  cluster-9.config.json.
// ============================================================================

import config from "./cluster-9.config.json";
import {
  AA_RED,
  WHITE,
  INK_950,
  MediaSlot,
  Frame,
  FixedDesign,
  ForegroundMedia,
} from "./_helpers.jsx";

export const WIDTH = config.width;
export const HEIGHT = config.height;

// Font preflight markers — required so renderer detects fonts referenced
// via _helpers.jsx imports. Add more entries here if you use other fonts.
const _FONT_PREFLIGHT = {
  display: { fontFamily: "'Anton', 'Oswald', sans-serif" },
  mono: { fontFamily: "'JetBrains Mono', ui-monospace, monospace" },
  body: { fontFamily: "'Geist', sans-serif" },
};

function cfg(id) {
  return config.elements.find((e) => e.id === id) || {};
}
function elStyle(id, extra) {
  const c = cfg(id);
  const style = {
    position: "absolute",
    left: c.x,
    top: c.y,
    fontSize: c.fontSize,
    fontFamily: c.fontFamily ? `'${c.fontFamily}', sans-serif` : undefined,
    color: c.color,
    ...extra,
  };
  if (c.strokeWidth) {
    style.WebkitTextStroke = `${c.strokeWidth}px ${c.strokeColor || WHITE}`;
  }
  return style;
}

const media = config.media || {};
const foreground = config.foregroundMedia || {};

function Cluster9() {
  return (
    <Frame width={WIDTH} height={HEIGHT} background={INK_950}>
      <MediaSlot
        path={media.path}
        offsetX={media.offsetX || 0}
        offsetY={media.offsetY || 0}
        scale={media.scale || 1}
        videoStartTime={media.videoStartTime || 0}
        crop={media.crop}
        width={WIDTH}
        height={HEIGHT}
      />

      <FixedDesign items={config.fixedDesign || []} />

      {/* Editable text elements (add via editor or by hand in config.elements) */}
      {config.elements.map((el) => (
        <div key={el.id} style={elStyle(el.id, {
          lineHeight: 1.0,
          letterSpacing: "-0.01em",
          whiteSpace: "pre",
        })}>
          {el.text}
        </div>
      ))}

      <ForegroundMedia
        path={foreground.path}
        offsetX={foreground.offsetX || 0}
        offsetY={foreground.offsetY || 0}
        scale={foreground.scale || 1}
        blendMode={foreground.blendMode || "normal"}
        width={WIDTH}
        height={HEIGHT}
      />
    </Frame>
  );
}

export default Cluster9;
