// FRESH-GENSLICE-TEST-AA-ANGLE-1-TIRED-REPS-F1 — static — action-hero.
// Generated by the generation engine (thin slice), guided by example ex-029-action-hero:
// full-bleed athlete photo, top-down gradient for legibility, mono eyebrow chip, and a
// giant Anton hook as the dominant element. Brand poured from the AA kit; copy verbatim
// (hook = copy-library ad-1.altHook.4). Role-annotated + promotable.

import config from "./fresh-genslice-test-aa-angle-1-tired-reps-F1.config.json";
import { LayerStack } from "./_helpers.jsx";

export const WIDTH = config.width;
export const HEIGHT = config.height;

// Font preflight markers — the renderer scans THIS entry file for literal
// fontFamily strings; fonts referenced only via config are invisible to it.
const _FONT_PREFLIGHT = {
  display: { fontFamily: "Anton" },
  mono: { fontFamily: "'JetBrains Mono', ui-monospace, monospace" },
};

function FreshGensliceF1() {
  return <LayerStack config={config} />;
}

export default FreshGensliceF1;
