// ============================================================================
//  scripts/lib/copy-resolve.mjs — expand copy REFERENCES into verbatim TEXT
// ============================================================================
//  The planner SELECTS copy by id (asset.copyRefs / asset.hookRef into the
//  campaign's copy-library.json); it never authors copy. This module turns those
//  ids into the verbatim text that assemble() places — BEFORE assemble runs, so
//  assemble only ever sees text (never a literal id renders on a creative).
//
//  NODE-ONLY. Never import from a .jsx/browser file — resolution runs in
//  run-campaign / fill-core (Node) before window.__CONFIG__ is injected.
//
//  Responsibilities:
//   • resolveCopyRef  — id → { text, unit } | null  (missing id is the caller's
//                       cue to WARN + fall back to the legacy headline path)
//   • resolveTokens   — interpolate {{location.name}} etc. against tier tags
//                       (the fill path has NO mustache support otherwise)
//   • buildRefPools   — asset.copyRefs + asset.hookRef (split) → role→[text] pools
//                       + a provenance set for the guard. The too-long ladder
//                       (main hook → shorter alt-hook → split → warn) lives here.
//   • verbatimGuard   — every content-slot string must trace to copy Cody wrote
//                       (provenance) or be a hand-edit; else it's flagged.
// ============================================================================

import { BEAT_HEADLINE_ROLE, beatLetter, splitHook, ROLES } from "./roles.mjs";

// Roles whose copy is the campaign's MESSAGE (must be verbatim-from-docs).
// Identity/structural roles (eyebrow anchor, brand, guarantee, cta, byline) are
// generated by the cascade and exempt from the verbatim guard.
export const CONTENT_ROLES = new Set([
  "kicker", "hook", "claim", "mechanism", "reframe", "proof", "stat", "testimonial",
]);

const isStr = (v) => typeof v === "string" && v.trim();
const norm = (s) => String(s).replace(/\s+/g, " ").trim();

// ---------------------------------------------------------------------------
// Tokens
// ---------------------------------------------------------------------------

// "CARMEL, IN" → "Carmel" (strip state suffix, title-case words).
function cityToName(city) {
  const base = String(city || "").replace(/,\s*[A-Za-z]{2}\.?$/, "").trim();
  if (!base) return "";
  return base.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());
}

// Tokens we can resolve from tier tags. {{user.first_name}} is intentionally NOT
// resolved — it's delivery-time personalization, left untouched on purpose.
const TOKEN_RESOLVERS = {
  "location.name": (t) => cityToName(t.city),
  "location.city": (t) => cityToName(t.city),
};

export function resolveTokens(text, tierTags = {}, warn) {
  return String(text).replace(/\{\{\s*([\w.]+)\s*\}\}/g, (m, key) => {
    const r = TOKEN_RESOLVERS[key];
    if (r) {
      const v = r(tierTags);
      if (isStr(v)) return v;
    }
    if (warn) warn(`unresolved merge token ${m}`);
    return m; // leave untouched — never render a wrong value
  });
}

// ---------------------------------------------------------------------------
// Reference resolution
// ---------------------------------------------------------------------------

// ref: an id string ("ad-2.imageHeadline") or { id }. Returns { text, unit } or
// null when the library is absent or the id is unknown.
export function resolveCopyRef(ref, library) {
  if (!library || !library.byId) return null;
  const id = typeof ref === "string" ? ref : ref && ref.id;
  if (!isStr(id)) return null;
  const unit = library.byId[id];
  if (!unit || !isStr(unit.text)) return null;
  return { text: unit.text, unit };
}

// The asset's hook source, resolved verbatim, with the too-long ladder applied.
// Returns { text, segments, usedRef } or null. `maxChars` (static slots only)
// triggers: main hook over budget → try a shorter alt-hook from the SAME ad →
// else split across kicker/headline/subhead. Words are never reworded/truncated.
function resolveHook(asset, library, { maxChars, warn } = {}) {
  if (!asset || !isStr(asset.hookRef)) return null;
  const primary = resolveCopyRef(asset.hookRef, library);
  if (!primary) {
    if (warn) warn(`hookRef "${asset.hookRef}" not in copy-library — falling back`);
    return null;
  }

  let chosen = primary;
  // Ladder step 2: if over a known budget, prefer a shorter alt-hook of the same ad.
  if (maxChars && primary.text.length > maxChars && primary.unit.ad) {
    const alts = (library.units || [])
      .filter((u) => u.kind === "altHook" && u.ad === primary.unit.ad)
      .sort((a, b) => a.chars - b.chars);
    const fit = alts.find((u) => u.chars <= maxChars) || alts[0];
    if (fit && fit.chars < primary.text.length) chosen = { text: fit.text, unit: fit };
  }

  // Ladder step 3: lay the chosen hook across the three slots.
  const segments = splitHook(chosen.text);
  return { text: chosen.text, segments, usedRef: chosen.unit.id };
}

// Build role→[text] pools from asset.copyRefs + asset.hookRef. Returns:
//   { pools, provenance:Set<normalized text>, refsUsed, warnings }
// Returns null when the asset carries NO references (caller uses the legacy
// buildCopyByRole(asset) path — back-compat for old plans / no copy-library).
export function buildRefPools(asset, { library, tierTags = {}, maxChars, warn = () => {} } = {}) {
  const hasRefs = asset && (asset.hookRef || (asset.copyRefs && Object.keys(asset.copyRefs).length));
  if (!library || !hasRefs) return null;

  const pools = {};
  const provenance = new Set();
  const refsUsed = [];
  const add = (role, raw) => {
    if (!CONTENT_ROLES.has(role) && !ROLES.includes(role)) return;
    const text = resolveTokens(raw, tierTags, (m) => warn(`${asset.id || "?"}: ${m}`));
    if (!isStr(text)) return;
    (pools[role] = pools[role] || []).push(text);
    provenance.add(norm(text));
  };

  // Explicit role-keyed references (value = id or [id, ...]).
  for (const [role, refOrList] of Object.entries(asset.copyRefs || {})) {
    for (const ref of [].concat(refOrList)) {
      const r = resolveCopyRef(ref, library);
      if (!r) { warn(`${asset.id || "?"}: copyRef "${typeof ref === "string" ? ref : ref?.id}" (${role}) not in copy-library`); continue; }
      add(role, r.text);
      refsUsed.push(r.unit.id);
    }
  }

  // Hook reference → laid across kicker / headline-role / reframe slots.
  const hook = resolveHook(asset, library, { maxChars, warn: (m) => warn(`${asset.id || "?"}: ${m}`) });
  if (hook) {
    const headRole = BEAT_HEADLINE_ROLE[beatLetter(asset.beat)] || "hook";
    if (isStr(hook.segments.kicker)) add("kicker", hook.segments.kicker);
    if (isStr(hook.segments.headline)) add(headRole, hook.segments.headline);
    if (isStr(hook.segments.subhead)) add("reframe", hook.segments.subhead);
    refsUsed.push(hook.usedRef);
  }

  return { pools, provenance, refsUsed, warnings: [] };
}

// ---------------------------------------------------------------------------
// Verbatim guard (report-only)
// ---------------------------------------------------------------------------

// placedBySlot: { slotId: { role, text } }. A content-role slot whose text does
// not trace to copy Cody wrote (provenance) is a VIOLATION — unless the asset was
// hand-edited (editedAt) or the text is in the library. Identity/structural roles
// are exempt. Returns an array of { slotId, role, text } violations (never throws).
export function verbatimGuard({ placedBySlot = {}, provenance = new Set(), library, asset } = {}) {
  if (asset && asset.editedAt) return []; // hand-edits are authoritative
  const libTexts = new Set();
  if (library && Array.isArray(library.units)) for (const u of library.units) libTexts.add(norm(u.text));
  const violations = [];
  for (const [slotId, info] of Object.entries(placedBySlot)) {
    if (!info || !CONTENT_ROLES.has(info.role) || !isStr(info.text)) continue;
    const t = norm(info.text);
    if (provenance.has(t) || libTexts.has(t)) continue;
    violations.push({ slotId, role: info.role, text: info.text });
  }
  return violations;
}
